"""📋 Weekly Briefing — Preview and manual trigger for weekly digest."""

import streamlit as st
from datetime import datetime

st.set_page_config(page_title="Weekly Briefing", page_icon="📋", layout="wide")
st.title("📋 Weekly Briefing")
st.caption("Fires every Sunday at 8:00 AM · Delivered via Telegram + Email")
st.divider()

# ── Status ────────────────────────────────────────────────────────────────────
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Schedule", "Sunday 8:00 AM")
with col2:
    st.metric("Last Run", "—")
with col3:
    st.metric("Next Run", "—")

st.divider()

# ── Manual trigger ────────────────────────────────────────────────────────────
st.markdown("### 🚀 Manual Trigger")
if st.button("▶️ Generate Briefing Now", type="primary"):
    st.info("⚙️ Weekly briefing agent — coming soon")

st.divider()

# ── Preview sections ──────────────────────────────────────────────────────────
st.markdown("### 📄 Briefing Sections")

sections = [
    ("📅 Next Week Appointments", "Upcoming tasks and appointments from your notes"),
    ("⏰ Upcoming Reminders", "Tasks due this week"),
    ("📈 Stock Earnings (next 4 weeks)", "Earnings calendar for your watchlist"),
    ("💳 Expense Glimpse (last 7 days)", "Spend summary from CC agent"),
    ("💬 Quote of the Week", "Generated by Qwen2.5"),
    ("😄 Joke", "Generated by Qwen2.5"),
    ("🖥️ System Health", "ChromaDB status, Ollama uptime, Tailscale latency"),
]

for title, desc in sections:
    with st.expander(title):
        st.caption(desc)
        st.info("⚙️ Coming soon")

st.divider()

# ── Delivery config ───────────────────────────────────────────────────────────
st.markdown("### ⚙️ Delivery Settings")
col4, col5 = st.columns(2)
with col4:
    st.toggle("Telegram", value=True)
    st.text_input("Telegram chat ID", placeholder="auto-configured via OpenClaw")
with col5:
    st.toggle("Email", value=False)
    st.text_input("Email address", placeholder="you@gmail.com")

if st.button("💾 Save Settings"):
    st.info("⚙️ Delivery config — coming soon")
