#!/usr/bin/env python3
"""
Send emails via Gmail SMTP.

Usage:
  send_email.py --to RECIPIENT --subject SUBJECT --body BODY [--cc CC] [--bcc BCC] [--html]

Arguments:
  --to         Recipient email address (required)
  --subject    Email subject (required)
  --body       Email body text or HTML (required)
  --cc         CC recipients, comma-separated (optional)
  --bcc        BCC recipients, comma-separated (optional)
  --html       Treat body as HTML instead of plain text (optional flag)

Environment:
  OPENCLAW_EMAIL              Sender email (from config.settings.openclaw_email)
  OPENCLAW_EMAIL_PASSWORD     Gmail App Password (from config.settings.openclaw_email_password)

Exit Codes:
  0  Success (prints SENT: <message_id>)
  1  Argument error
  2  Configuration missing
  3  SMTP connection/auth failure
  4  Email send failure

Outputs:
  - SENT: <message_id> on success
  - ERROR: <reason> on failure
  - Logs sent email to ~/AgenticHub/Persgraph/data/email_sent_log.jsonl
"""

import argparse
import json
import os
import sys
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
import smtplib

# Add PersGraph to path so we can import config
sys.path.insert(0, os.path.expanduser("~/AgenticHub/Persgraph"))

def load_config():
    """Load email credentials from PersGraph config."""
    try:
        from second_brain.config import settings
        sender = settings.openclaw_email
        password = settings.openclaw_email_password
        if not sender or not password:
            print("ERROR: openclock_email or openclock_email_password not configured in settings")
            sys.exit(2)
        return sender, password
    except ImportError as e:
        print(f"ERROR: Could not import PersGraph config: {e}")
        sys.exit(2)
    except AttributeError as e:
        print(f"ERROR: Config missing required fields: {e}")
        sys.exit(2)

def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Send email via Gmail SMTP",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument("--to", required=True, help="Recipient email address")
    parser.add_argument("--subject", required=True, help="Email subject")
    parser.add_argument("--body", required=True, help="Email body (text or HTML)")
    parser.add_argument("--cc", default="", help="CC recipients (comma-separated)")
    parser.add_argument("--bcc", default="", help="BCC recipients (comma-separated)")
    parser.add_argument("--html", action="store_true", help="Treat body as HTML")
    
    args = parser.parse_args()
    
    # Validate recipient
    if not args.to or "@" not in args.to:
        print("ERROR: --to must be a valid email address")
        sys.exit(1)
    
    return args

def send_email(sender, password, to, subject, body, cc="", bcc="", is_html=False):
    """
    Send email via Gmail SMTP.
    
    Returns:
        (success: bool, message_id: str or error_msg: str)
    """
    try:
        # Create message
        msg = MIMEMultipart("alternative")
        msg["From"] = sender
        msg["To"] = to
        msg["Subject"] = subject
        
        if cc:
            msg["Cc"] = cc
        
        # Add body
        content_type = "html" if is_html else "plain"
        msg.attach(MIMEText(body, content_type))
        
        # Prepare all recipients (including CC/BCC)
        recipients = [to]
        if cc:
            recipients.extend([e.strip() for e in cc.split(",")])
        if bcc:
            recipients.extend([e.strip() for e in bcc.split(",")])
        
        # Connect and send
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=10) as server:
            server.starttls()
            server.login(sender, password)
            result = server.sendmail(sender, recipients, msg.as_string())
        
        # Message-ID is generated by the server; we'll use timestamp + recipient hash
        message_id = f"{datetime.utcnow().isoformat()}_to_{to}"
        return True, message_id
    
    except smtplib.SMTPAuthenticationError as e:
        return False, f"Authentication failed (bad credentials): {e}"
    except smtplib.SMTPException as e:
        return False, f"SMTP error: {e}"
    except Exception as e:
        return False, f"Unexpected error: {e}"

def log_sent_email(sender, to, subject, cc="", bcc="", success=True, error_msg=""):
    """Log sent email to ~/AgenticHub/Persgraph/data/email_sent_log.jsonl"""
    log_dir = Path(os.path.expanduser("~/AgenticHub/Persgraph/data"))
    log_dir.mkdir(parents=True, exist_ok=True)
    
    log_file = log_dir / "email_sent_log.jsonl"
    
    entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "from": sender,
        "to": to,
        "cc": cc or None,
        "bcc": bcc or None,
        "subject": subject,
        "success": success,
        "error": error_msg or None
    }
    
    try:
        with open(log_file, "a") as f:
            f.write(json.dumps(entry) + "\n")
    except Exception as e:
        print(f"WARNING: Could not write to log file: {e}", file=sys.stderr)

def main():
    args = parse_args()
    sender, password = load_config()
    
    success, result = send_email(
        sender=sender,
        password=password,
        to=args.to,
        subject=args.subject,
        body=args.body,
        cc=args.cc,
        bcc=args.bcc,
        is_html=args.html
    )
    
    if success:
        print(f"SENT: {result}")
        log_sent_email(sender, args.to, args.subject, args.cc, args.bcc, success=True)
        sys.exit(0)
    else:
        print(f"ERROR: {result}")
        log_sent_email(sender, args.to, args.subject, args.cc, args.bcc, success=False, error_msg=result)
        sys.exit(3)

if __name__ == "__main__":
    main()
